 #!/bin/bash
eb setenv \
AWS_ACCESS_KEY_ID='' \
AWS_SECRET_ACCESS_KEY='' \
AWS_STORAGE_BUCKET_NAME='' \
AWS_S3_REGION_NAME='' \
RDS_DB_NAME='' \
RDS_USERNAME='' \
RDS_PASSWORD='' \
RDS_HOSTNAME='' \
RDS_PORT=''
